### PR TITLE
Remove resolution txn restrictions

### PR DESCRIPTION
**Pull request by n8maninger**
Removes the need for a setup transaction for v2 contract resolutions

### CODE REVIEW

**Comment by lukechampine** [comment]
Why *did* we need a setup transaction? Is it purely to pay the miner fee? If so, perhaps some of the funds in a contract resolution could be used to pay the fee...? 🤔

**Comment by n8maninger** [comment]
Renter allowance, host collateral, and miner fee.

**Comment by n8maninger** [comment]
Looks like this would also have a side-effect of enabling the host/renter rollover to "escape"...

**Comment by lukechampine** [comment]
Another option is to timelock the outputs, i.e. the change output from a resolution wouldn't be spendable for 144 blocks. That might be confusing from a UX perspective though.

**Comment by n8maninger** [comment]
@lukechampine are you okay with this as is?

**Comment by lukechampine** [comment]
yeah, I think so, as long as we're a bit more cautious about immediately chaining those outputs into new transactions.

**Comment by lukechampine** [comment]
c.f. https://github.com/SiaFoundation/core/pull/43...
I'm thinking that we should probably not allow contract outputs to be ephemeral. That's enough of a deterrent to prevent the most egregious forms of output chaining.

**Pull request merged**
