### PR TITLE
Add test coverage for ElementAccumulator.DecodeFrom

### PR DESCRIPTION
**Pull request by new0nebit**
This PR expands test coverage in merkle to 95.1% and overall consensus coverage to 76.2%
Now that we have the coverage for DecodeFrom and EncodeTo I'm planning to add a roundtrip later, assuming you find such tests to be valuable.

### CODE REVIEW

**Comment by lukechampine** [comment]
Let's do a roundtrip test instead

**Comment by new0nebit** [comment]
Great, I'll give it a try 🧐

**Comment by new0nebit** [comment]
Done! (ง •̀‿•́ )ง

**Review by lukechampine — APPROVED** [review]

**Comment by lukechampine** [comment]
thanks!

**Pull request merged**
